// Two curated packs of 50 quotes each

export const QUOTE_PACKS = {
    founders: {
        name: "American Founders",
        quotes: [
            { text: "The only way to be truly free is to make our own laws.", author: "Benjamin Franklin" },
            { text: "Give me liberty, or give me death!", author: "Patrick Henry" },
            { text: "We hold these truths to be self-evident, that all men are created equal.", author: "Thomas Jefferson" },
            { text: "The price of liberty is eternal vigilance.", author: "Thomas Jefferson" },
            { text: "In matters of style, swim with the current; in matters of principle, stand like a rock.", author: "Thomas Jefferson" },
            { text: "It is the soldier, not the reporter, who has given us freedom of the press.", author: "George Washington" },
            { text: "Associate yourself with men of good quality if you esteem your own reputation; for 'tis better to be alone than in bad company.", author: "George Washington" },
            { text: "Discipline is the soul of an army. It makes small numbers formidable.", author: "George Washington" },
            { text: "To be prepared for war is one of the most effective means of preserving peace.", author: "George Washington" },
            { text: "It is far better to be alone, than to be in bad company.", author: "George Washington" },
            { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
            { text: "Well done is better than well said.", author: "Benjamin Franklin" },
            { text: "No gains without pains.", author: "Benjamin Franklin" },
            { text: "A penny saved is a penny earned.", author: "Benjamin Franklin" },
            { text: "Tell me and I forget, teach me and I may remember, involve me and I learn.", author: "Benjamin Franklin" },
            { text: "The advancement and diffusion of knowledge is the only guardian of true liberty.", author: "James Madison" },
            { text: "Knowledge will forever govern ignorance; and a people who mean to be their own governors must arm themselves with the power which knowledge gives.", author: "James Madison" },
            { text: "If men were angels, no government would be necessary.", author: "James Madison" },
            { text: "It is a universal truth that the loss of liberty at home is to be charged to the provisions against danger, real or pretended, from abroad.", author: "James Madison" },
            { text: "The truth is that all men having power ought to be mistrusted.", author: "James Madison" },
            { text: "I have more respect for a man who lets me know where he stands, even if he's wrong, than the one who comes up like an angel and is nothing but a devil.", author: "Thomas Paine" },
            { text: "The strength and power of despotism consists wholly in the fear of resistance.", author: "Thomas Paine" },
            { text: "We have it in our power to begin the world over again.", author: "Thomas Paine" },
            { text: "The world is my country, all mankind are my brethren, and to do good is my religion.", author: "Thomas Paine" },
            { text: "Character is like a tree and reputation like a shadow. The shadow is what we think of it; the tree is the real thing.", author: "Abraham Lincoln" },
            { text: "America will never be destroyed from the outside. If we falter and lose our freedoms, it will be because we destroyed ourselves.", author: "Abraham Lincoln" },
            { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
            { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
            { text: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", author: "Abraham Lincoln" },
            { text: "Those who deny freedom to others deserve it not for themselves.", author: "Abraham Lincoln" },
            { text: "Facts are stubborn things; and whatever may be our wishes, our inclinations, or the dictates of our passions, they cannot alter the state of facts and evidence.", author: "John Adams" },
            { text: "The happiness of society is the end of government.", author: "John Adams" },
            { text: "Old minds are like old horses; you must exercise them if you wish to keep them in working condition.", author: "John Adams" },
            { text: "Power always thinks it has a great soul and vast views beyond the comprehension of the weak.", author: "John Adams" },
            { text: "Liberty cannot be preserved without a general knowledge among the people.", author: "John Adams" },
            { text: "The noblest motive is the public good.", author: "Virgil Mason" },
            { text: "A republic, if you can keep it.", author: "Benjamin Franklin" },
            { text: "One man with courage is a majority.", author: "Andrew Jackson" },
            { text: "Take time to deliberate; but when the time for action arrives, stop thinking and go in.", author: "Andrew Jackson" },
            { text: "There is no pleasure in having nothing to do; the fun is in having lots to do and not doing it.", author: "Mary Wilson Little" },
            { text: "The battle, sir, is not to the strong alone; it is to the vigilant, the active, the brave.", author: "Patrick Henry" },
            { text: "Free government is founded in jealousy, and not in confidence.", author: "Thomas Jefferson" },
            { text: "Our Constitution was made only for a moral and religious People. It is wholly inadequate to the government of any other.", author: "John Adams" },
            { text: "Happiness depends more on the inward disposition of mind than on outward circumstances.", author: "Benjamin Franklin" },
            { text: "Diligence is the mother of good luck.", author: "Benjamin Franklin" },
            { text: "Liberty is to the collective body what health is to every individual body.", author: "Voltaire" },
            { text: "Laws and institutions must go hand in hand with the progress of the human mind.", author: "Thomas Jefferson" },
            { text: "Honesty is the first chapter in the book of wisdom.", author: "Thomas Jefferson" },
            { text: "The will of the people is the only legitimate foundation of any government.", author: "Thomas Jefferson" },
            { text: "If you want something done right, do it yourself.", author: "George Washington" },
            // John Marshall Quotes
            { text: "To listen well is as powerful a means of communication and influence as to talk well.", author: "John Marshall" },
            { text: "The Constitution is either a superior paramount law, unchangeable by ordinary means, or it is on a level with ordinary legislative acts.", author: "John Marshall" },
            { text: "The peculiar circumstances of the moment may render a measure more or less wise, but cannot render it more or less constitutional.", author: "John Marshall" },
            { text: "An unlimited power to tax involves, necessarily, a power to destroy.", author: "John Marshall" },
            { text: "It is emphatically the province and duty of the judicial department to say what the law is.", author: "John Marshall" },
            { text: "The power to tax involves the power to destroy.", author: "John Marshall" },
            { text: "A constitution is framed for ages to come, and is designed to approach immortality as nearly as human institutions can approach it.", author: "John Marshall" },
            { text: "We must never forget that it is a constitution we are expounding.", author: "John Marshall" },
            { text: "The government of the Union, though limited in its powers, is supreme within its sphere of action.", author: "John Marshall" },
            { text: "Let the end be legitimate, let it be within the scope of the constitution, and all means which are appropriate, which are plainly adapted to that end... are constitutional.", author: "John Marshall" },
            { text: "Every man's house is his castle.", author: "John Marshall" },
            { text: "There is no such thing as a free lunch.", author: "John Marshall" },
            { text: "A law repugnant to the Constitution is void.", author: "John Marshall" },
            { text: "The people made the Constitution, and the people can unmake it.", author: "John Marshall" },
            { text: "The acme of judicial distinction means the ability to look a lawyer straight in the eyes for two hours and not to hear a damned word he says.", author: "John Marshall" },
            { text: "No man's life, liberty or property are safe while the Legislature is in session.", author: "John Marshall" },
            { text: "It is a constitution intended to endure for ages to come, and, consequently, to be adapted to the various crises of human affairs.", author: "John Marshall" },
            { text: "In America, the law is king. For as in absolute governments the King is law, so in free countries the law ought to be King.", author: "John Marshall" },
            { text: "If a law be in opposition to the constitution; if both the law and the constitution apply to a particular case... the court must determine which of these conflicting rules governs the case.", author: "John Marshall" },
            { text: "The very essence of civil liberty certainly consists in the right of every individual to claim the protection of the laws, whenever he receives an injury.", author: "John Marshall" },
            { text: "The judicial department comes home in its effects to every man's fireside: it passes on his property, his reputation, his life, his all.", author: "John Marshall" },
            { text: "A corporation is an artificial being, invisible, intangible, and existing only in contemplation of law.", author: "John Marshall" },
            { text: "Experience should teach us to be most on our guard to protect liberty when the government's purposes are beneficent.", author: "John Marshall" },
            { text: "To what quarter will you look for protection from an infringement on the Constitution, if you will not give the power to the judiciary?", author: "John Marshall" },
            { text: "The Constitution of the United States was made not merely for the generation that then existed, but for posterity.", author: "John Marshall" },
        ]
    },
    rumi: {
        name: "Rumi",
        quotes: [
            { text: "Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.", author: "Rumi" },
            { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
            { text: "You were born with wings. Why prefer to crawl through life?", author: "Rumi" },
            { text: "The wound is the place where the Light enters you.", author: "Rumi" },
            { text: "Sell your cleverness and buy bewilderment.", author: "Rumi" },
            { text: "Do not be satisfied with the stories that come before you. Unfold your own myth.", author: "Rumi" },
            { text: "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.", author: "Rumi" },
            { text: "Why do you stay in prison when the door is so wide open?", author: "Rumi" },
            { text: "Travel brings power and love back into your life.", author: "Rumi" },
            { text: "Take someone who doesn't keep score, who's not looking to be richer, or afraid of losing, who has not the slightest interest even in his own personality: he's free.", author: "Rumi" },
            { text: "Ignore those that make you fearful and sad, that degrade you back towards disease and death.", author: "Rumi" },
            { text: "The garden of the world has no limits, except in your mind.", author: "Rumi" },
            { text: "Raise your words, not voice. It is rain that grows flowers, not thunder.", author: "Rumi" },
            { text: "Silence is the language of God, all else is poor translation.", author: "Rumi" },
            { text: "What you seek is seeking you.", author: "Rumi" },
            { text: "The Prophets accept all agony and trust it. For the water has never feared the fire.", author: "Rumi" },
            { text: "Be a lamp, or a lifeboat, or a ladder. Help someone's soul heal. Walk out of your house like a shepherd.", author: "Rumi" },
            { text: "Shine like the whole universe is yours.", author: "Rumi" },
            { text: "Let the beauty of what you love be what you do.", author: "Rumi" },
            { text: "Every moment I shape my destiny with a chisel — I am the carpenter of my own soul.", author: "Rumi" },
            { text: "When you do things from your soul, you feel a river moving in you, a joy.", author: "Rumi" },
            { text: "I am not this hair, I am not this skin, I am the soul that lives within.", author: "Rumi" },
            { text: "Your heart is the size of an ocean. Go find yourself in its hidden depths.", author: "Rumi" },
            { text: "The lion is most handsome when looking for food.", author: "Rumi" },
            { text: "You have to keep breaking your heart until it opens.", author: "Rumi" },
            { text: "If you are irritated by every rub, how will you get polished?", author: "Rumi" },
            { text: "Everything in the universe is within you. Ask all from yourself.", author: "Rumi" },
            { text: "Be empty of worrying. Think of who created thought.", author: "Rumi" },
            { text: "Be grateful for whoever comes, because each has been sent as a guide from beyond.", author: "Rumi" },
            { text: "Patience is the key to joy.", author: "Rumi" },
            { text: "Dance, when you're broken open. Dance, if you've torn the bandage off.", author: "Rumi" },
            { text: "Try not to resist the changes that come your way. Instead, let life live through you.", author: "Rumi" },
            { text: "Sorrow prepares you for joy. It violently sweeps everything out of your house.", author: "Rumi" },
            { text: "Stop acting so small. You are the universe in ecstatic motion.", author: "Rumi" },
            { text: "Words are a pretext. It is the inner bond that draws one person to another.", author: "Rumi" },
            { text: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", author: "Rumi" },
            { text: "Wherever you are, and whatever you do, be in love.", author: "Rumi" },
            { text: "Only from the heart can you touch the sky.", author: "Rumi" },
            { text: "The art of knowing is knowing what to ignore.", author: "Rumi" },
            { text: "Gratitude is the wine for the soul. Go on. Get drunk.", author: "Rumi" },
            { text: "Yesterday is gone and its tale told. Today new seeds are growing.", author: "Rumi" },
            { text: "Forget safety. Live where you fear to live.", author: "Rumi" },
            { text: "Study me as much as you like, you will not know me, for I differ in a hundred ways from what you see me to be.", author: "Rumi" },
            { text: "Seek the wisdom that will untie your knot. Seek the path that demands your whole being.", author: "Rumi" },
            { text: "There is a voice that doesn't use words. Listen.", author: "Rumi" },
            { text: "In silence there is eloquence. Stop weaving and see how the pattern improves.", author: "Rumi" },
            { text: "A thousand half-loves must be forsaken to take one whole heart home.", author: "Rumi" },
            { text: "This human being is a guest house. Every morning a new arrival.", author: "Rumi" },
            { text: "Wherever you stand, be the soul of that place.", author: "Rumi" },
            { text: "When you feel a peaceful joy, that's when you are near truth.", author: "Rumi" },
            { text: "The cure for pain is in the pain.", author: "Rumi" },
        ]
    }
} as const;

export type QuotePackId = keyof typeof QUOTE_PACKS;

export function getQuoteForTime(packId: QuotePackId = 'founders'): { text: string; author: string } {
    const pack = QUOTE_PACKS[packId];
    // Rotate every 4 hours based on timestamp
    const fourHourBlock = Math.floor(Date.now() / (1000 * 60 * 60 * 4));
    const index = fourHourBlock % pack.quotes.length;
    return pack.quotes[index];
}
